/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.com.gepp.cliente;

/**
 *
 * @author OCA
 */
public class DetallesViaje extends javax.swing.JFrame {

    /**
     * Creates new form detalles
     */
    //variable para leer nombre de json
    public static String nombreJson;

    public DetallesViaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloJson = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cabecera_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        traspInter_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaGen_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        usoCFDI_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        docsGEPP_text = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        folioGEPP_text = new javax.swing.JTextField();
        version_text = new javax.swing.JTextField();
        totalDist_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        oc_text = new javax.swing.JTextField();
        ubicaciones_panel = new javax.swing.JPanel();
        ubicacionOrigen_panel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tipoUbi_text = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        idUbi_text = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        rfcUbi_text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        fechaHora_text = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        distanciaRec_text = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        calle_text = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        numExt_text = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        colonia_text = new javax.swing.JTextField();
        localidad_text = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        estado_text = new javax.swing.JTextField();
        municipio_text = new javax.swing.JTextField();
        pais_text = new javax.swing.JTextField();
        cp_text = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OR_text = new javax.swing.JTextField();
        ubicacionDestino_panel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        tipoDestino_text = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        idDestino_text = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        rfcDestino_text = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        fechaHoraDestino_text = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        distaRecDestino_text = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        calleDestino_text = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        numExtDes_text = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        coloniaDestino_text = new javax.swing.JTextField();
        localidadDestino_text = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        estadoDestino_text = new javax.swing.JTextField();
        municipioDestino_text = new javax.swing.JTextField();
        paisDestino_text = new javax.swing.JTextField();
        cpDestino_text = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DE_text = new javax.swing.JTextField();
        panelMercancias = new javax.swing.JPanel();
        datosGenerales_panel = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        pesoBruto_text = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        pesoNeto_text = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        unidadPeso_text = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        totalMercan_text = new javax.swing.JTextField();
        mercancias_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mercancias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_inicio.setBackground(new java.awt.Color(204, 204, 204));
        panel_inicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DETALLES DEL VIAJE");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Folio GEPP:");

        tituloJson.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        tituloJson.setForeground(new java.awt.Color(0, 102, 204));
        tituloJson.setText("Identificador del viaje");

        javax.swing.GroupLayout panel_inicioLayout = new javax.swing.GroupLayout(panel_inicio);
        panel_inicio.setLayout(panel_inicioLayout);
        panel_inicioLayout.setHorizontalGroup(
            panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inicioLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_inicioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloJson, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_inicioLayout.setVerticalGroup(
            panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tituloJson))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cabecera_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CABECERA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel4.setText("Folio GEPP");

        traspInter_text.setEditable(false);

        jLabel7.setText("Fecha Generación");

        fechaGen_text.setEditable(false);

        jLabel8.setText("Uso CFDI");

        usoCFDI_text.setEditable(false);

        jLabel10.setText("Documentos GEPP");

        docsGEPP_text.setEditable(false);
        docsGEPP_text.setColumns(20);
        docsGEPP_text.setRows(5);
        jScrollPane2.setViewportView(docsGEPP_text);

        jLabel9.setText("Versión Carta Porte");

        jLabel11.setText("Transporte Internacional");

        jLabel12.setText("Total Distancia Recorrida");

        folioGEPP_text.setEditable(false);

        version_text.setEditable(false);

        totalDist_text.setEditable(false);
        totalDist_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDist_textActionPerformed(evt);
            }
        });

        jLabel3.setText("OC");

        oc_text.setEditable(false);

        javax.swing.GroupLayout cabecera_panelLayout = new javax.swing.GroupLayout(cabecera_panel);
        cabecera_panel.setLayout(cabecera_panelLayout);
        cabecera_panelLayout.setHorizontalGroup(
            cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_panelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(folioGEPP_text, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(fechaGen_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecera_panelLayout.createSequentialGroup()
                        .addComponent(usoCFDI_text, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalDist_text, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cabecera_panelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel12))
                    .addGroup(cabecera_panelLayout.createSequentialGroup()
                        .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oc_text, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(version_text, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(traspInter_text, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(596, Short.MAX_VALUE))
        );
        cabecera_panelLayout.setVerticalGroup(
            cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecera_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(folioGEPP_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oc_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(traspInter_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(version_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cabecera_panelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(cabecera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaGen_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usoCFDI_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDist_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        ubicaciones_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UBICACIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        ubicacionOrigen_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Origen"));

        jLabel24.setText("Tipo");

        tipoUbi_text.setEditable(false);

        jLabel25.setText("ID Ubicación");

        idUbi_text.setEditable(false);

        jLabel26.setText("RFC");

        rfcUbi_text.setEditable(false);

        jLabel31.setText("Fecha y hora");

        fechaHora_text.setEditable(false);

        jLabel32.setText("Distancia recorrida");

        distanciaRec_text.setEditable(false);

        jLabel33.setText("Calle");

        calle_text.setEditable(false);

        jLabel34.setText("Numero Exterior");

        numExt_text.setEditable(false);

        jLabel35.setText("Colonia");

        colonia_text.setEditable(false);

        localidad_text.setEditable(false);

        jLabel36.setText("Municipio");

        estado_text.setEditable(false);

        municipio_text.setEditable(false);

        pais_text.setEditable(false);

        cp_text.setEditable(false);

        jLabel37.setText("País");

        jLabel38.setText("Estado");

        jLabel39.setText("Código postal");

        jLabel40.setText("Localidad");

        jLabel5.setText("OR:");

        javax.swing.GroupLayout ubicacionOrigen_panelLayout = new javax.swing.GroupLayout(ubicacionOrigen_panel);
        ubicacionOrigen_panel.setLayout(ubicacionOrigen_panelLayout);
        ubicacionOrigen_panelLayout.setHorizontalGroup(
            ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OR_text, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                        .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calle_text)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(municipio_text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ubicacionOrigen_panelLayout.createSequentialGroup()
                                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(tipoUbi_text, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idUbi_text, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))))
                        .addGap(34, 34, 34)
                        .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                                .addComponent(estado_text, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233)
                                .addComponent(cp_text))
                            .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                                        .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51))
                                    .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                                        .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(numExt_text, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rfcUbi_text))
                                        .addGap(27, 27, 27)))
                                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                                        .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel35)
                                            .addGroup(ubicacionOrigen_panelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(fechaHora_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubicacionOrigen_panelLayout.createSequentialGroup()
                                        .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pais_text, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(colonia_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(localidad_text, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(distanciaRec_text))))))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        ubicacionOrigen_panelLayout.setVerticalGroup(
            ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubicacionOrigen_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(OR_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoUbi_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idUbi_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfcUbi_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaHora_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distanciaRec_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numExt_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colonia_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidad_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(ubicacionOrigen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pais_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ubicacionDestino_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));

        jLabel27.setText("Tipo");

        tipoDestino_text.setEditable(false);

        jLabel28.setText("ID Ubicación");

        idDestino_text.setEditable(false);

        jLabel29.setText("RFC");

        rfcDestino_text.setEditable(false);

        jLabel41.setText("Fecha y hora");

        fechaHoraDestino_text.setEditable(false);

        jLabel42.setText("Distancia recorrida");

        distaRecDestino_text.setEditable(false);

        jLabel43.setText("Calle");

        calleDestino_text.setEditable(false);

        jLabel44.setText("Numero Exterior");

        numExtDes_text.setEditable(false);

        jLabel45.setText("Colonia");

        coloniaDestino_text.setEditable(false);

        localidadDestino_text.setEditable(false);

        jLabel46.setText("Municipio");

        estadoDestino_text.setEditable(false);

        municipioDestino_text.setEditable(false);

        paisDestino_text.setEditable(false);

        cpDestino_text.setEditable(false);

        jLabel47.setText("País");

        jLabel48.setText("Estado");

        jLabel49.setText("Código postal");

        jLabel50.setText("Localidad");

        jLabel13.setText("DE:");

        javax.swing.GroupLayout ubicacionDestino_panelLayout = new javax.swing.GroupLayout(ubicacionDestino_panel);
        ubicacionDestino_panel.setLayout(ubicacionDestino_panelLayout);
        ubicacionDestino_panelLayout.setHorizontalGroup(
            ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                        .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calleDestino_text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tipoDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(106, 106, 106)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)))
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(municipioDestino_text))
                        .addGap(34, 34, 34)
                        .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoDestino_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel44)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rfcDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numExtDes_text, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel45)
                                    .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fechaHoraDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubicacionDestino_panelLayout.createSequentialGroup()
                                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(paisDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coloniaDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel42)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distaRecDestino_text)
                            .addComponent(localidadDestino_text)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubicacionDestino_panelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cpDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(DE_text, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ubicacionDestino_panelLayout.setVerticalGroup(
            ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubicacionDestino_panelLayout.createSequentialGroup()
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DE_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfcDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaHoraDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distaRecDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calleDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numExtDes_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coloniaDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidadDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49))
                .addGap(18, 18, 18)
                .addGroup(ubicacionDestino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipioDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisDestino_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ubicaciones_panelLayout = new javax.swing.GroupLayout(ubicaciones_panel);
        ubicaciones_panel.setLayout(ubicaciones_panelLayout);
        ubicaciones_panelLayout.setHorizontalGroup(
            ubicaciones_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubicaciones_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubicaciones_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubicaciones_panelLayout.createSequentialGroup()
                        .addComponent(ubicacionOrigen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(ubicaciones_panelLayout.createSequentialGroup()
                        .addComponent(ubicacionDestino_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        ubicaciones_panelLayout.setVerticalGroup(
            ubicaciones_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubicaciones_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ubicacionOrigen_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ubicacionDestino_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMercancias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MERCANCIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        datosGenerales_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos generales"));

        jLabel51.setText("Peso Bruto Total");

        pesoBruto_text.setEditable(false);

        jLabel52.setText("Unidad Peso");

        pesoNeto_text.setEditable(false);

        jLabel53.setText("Numero total de marcancias");

        unidadPeso_text.setEditable(false);

        jLabel54.setText("Peso Neto Total");

        totalMercan_text.setEditable(false);

        javax.swing.GroupLayout datosGenerales_panelLayout = new javax.swing.GroupLayout(datosGenerales_panel);
        datosGenerales_panel.setLayout(datosGenerales_panelLayout);
        datosGenerales_panelLayout.setHorizontalGroup(
            datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosGenerales_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(pesoBruto_text, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(unidadPeso_text, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addComponent(pesoNeto_text, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalMercan_text))
                .addContainerGap(787, Short.MAX_VALUE))
        );
        datosGenerales_panelLayout.setVerticalGroup(
            datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosGenerales_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosGenerales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoBruto_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoNeto_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadPeso_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMercan_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mercancias_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mercancias"));

        tbl_mercancias = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_mercancias.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {

            },
            new String [] {
                "Bienes Trans", "Descripción", "Cantidad", "Clave Unidad", "Unidad", "Material Peligroso", "Peso (KG)", "Valor", "Moneda", "Fracción Arancelaria", "UUID Comercio Ext"
            }
        )
    );
    tbl_mercancias.setCellSelectionEnabled(true);
    tbl_mercancias.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(tbl_mercancias);
    tbl_mercancias.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    javax.swing.GroupLayout mercancias_panelLayout = new javax.swing.GroupLayout(mercancias_panel);
    mercancias_panel.setLayout(mercancias_panelLayout);
    mercancias_panelLayout.setHorizontalGroup(
        mercancias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mercancias_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1))
    );
    mercancias_panelLayout.setVerticalGroup(
        mercancias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mercancias_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelMercanciasLayout = new javax.swing.GroupLayout(panelMercancias);
    panelMercancias.setLayout(panelMercanciasLayout);
    panelMercanciasLayout.setHorizontalGroup(
        panelMercanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelMercanciasLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelMercanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(datosGenerales_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mercancias_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    panelMercanciasLayout.setVerticalGroup(
        panelMercanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelMercanciasLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(datosGenerales_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(mercancias_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cabecera_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ubicaciones_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMercancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(cabecera_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(ubicaciones_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addComponent(panelMercancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jScrollPane4.setViewportView(jPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1410, Short.MAX_VALUE)
            .addContainerGap())
        .addComponent(panel_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(panel_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addGap(43, 43, 43))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalDist_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDist_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDist_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField DE_text;
    public static javax.swing.JTextField OR_text;
    private javax.swing.JPanel cabecera_panel;
    public static javax.swing.JTextField calleDestino_text;
    public static javax.swing.JTextField calle_text;
    public static javax.swing.JTextField coloniaDestino_text;
    public static javax.swing.JTextField colonia_text;
    public static javax.swing.JTextField cpDestino_text;
    public static javax.swing.JTextField cp_text;
    private javax.swing.JPanel datosGenerales_panel;
    public static javax.swing.JTextField distaRecDestino_text;
    public static javax.swing.JTextField distanciaRec_text;
    public static javax.swing.JTextArea docsGEPP_text;
    public static javax.swing.JTextField estadoDestino_text;
    public static javax.swing.JTextField estado_text;
    public static javax.swing.JTextField fechaGen_text;
    public static javax.swing.JTextField fechaHoraDestino_text;
    public static javax.swing.JTextField fechaHora_text;
    public static javax.swing.JTextField folioGEPP_text;
    public static javax.swing.JTextField idDestino_text;
    public static javax.swing.JTextField idUbi_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextField localidadDestino_text;
    public static javax.swing.JTextField localidad_text;
    private javax.swing.JPanel mercancias_panel;
    public static javax.swing.JTextField municipioDestino_text;
    public static javax.swing.JTextField municipio_text;
    public static javax.swing.JTextField numExtDes_text;
    public static javax.swing.JTextField numExt_text;
    public static javax.swing.JTextField oc_text;
    public static javax.swing.JTextField paisDestino_text;
    public static javax.swing.JTextField pais_text;
    private javax.swing.JPanel panelMercancias;
    private javax.swing.JPanel panel_inicio;
    public static javax.swing.JTextField pesoBruto_text;
    public static javax.swing.JTextField pesoNeto_text;
    public static javax.swing.JTextField rfcDestino_text;
    public static javax.swing.JTextField rfcUbi_text;
    public static javax.swing.JTable tbl_mercancias;
    public static javax.swing.JTextField tipoDestino_text;
    public static javax.swing.JTextField tipoUbi_text;
    public static javax.swing.JLabel tituloJson;
    public static javax.swing.JTextField totalDist_text;
    public static javax.swing.JTextField totalMercan_text;
    public static javax.swing.JTextField traspInter_text;
    private javax.swing.JPanel ubicacionDestino_panel;
    private javax.swing.JPanel ubicacionOrigen_panel;
    private javax.swing.JPanel ubicaciones_panel;
    public static javax.swing.JTextField unidadPeso_text;
    public static javax.swing.JTextField usoCFDI_text;
    public static javax.swing.JTextField version_text;
    // End of variables declaration//GEN-END:variables
}
